export { StudentsLayout } from "./components/students/StudentsLayout.tsx"
export { TeacherLayout } from "./components/teachers/TeacherLayout.tsx"
export { TeacherProfileLayout } from "./components/teachers/TeacherProfile.tsx"
export { StudentProfileDetailsLayout } from "./components/students/components/StudentProfileDetailsLayout.tsx"
export { ParentsLayout } from "./components/parents/ParentsLayout.tsx"

export { StudentProfileAttendance } from "./components/students/ui/StudentProfileAttendance.tsx"
export { StudentProfileGrades } from "./components/students/ui/StudentProfileGrades.tsx"
export { StudentProfileClasses } from "./components/students/ui/StudentProfileClasses.tsx"
export { StudentProfileGeneral } from "./components/students/ui/StudentProfileGeneral.tsx"
export { StudentProfileSecurity } from "./components/students/ui/StudentProfileSecurity.tsx"